management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  okhttp:
    enabled: true
ribbon:
  ConnectTimeout: 3000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）


oauth2:
      client-id: code-community
      client-password: 123456
      keypair-password: 123456
      keypair-fileName: cc-jwt.jks

