spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/code_community?characterEncoding=UTF-8&useUnicode=true
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    timeout: 2000
    database: 0
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 3
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:dao/*.xml
  global-config:
    db-config:
      logic-delete-field: state  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)

management:
  endpoints:
    web:
      exposure:
        include: '*'