spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: cc-auth
          uri: lb://auth
          predicates:
            - Path=/cc-auth/**
          filters:
            - StripPrefix=1
        - id: cc-user
          uri: lb://user
          predicates:
            - Path=/cc-user/**
          filters:
            - StripPrefix=1
        - id: cc-blog
          uri: lb://blog
          predicates:
            - Path=/cc-blog/**
          filters:
            - StripPrefix=1
        - id: cc-comment
          uri: lb://comment
          predicates:
            - Path=/cc-comment/**
          filters:
            - StripPrefix=1
        - id: cc-question
          uri: lb://test
          predicates:
            - Path=/cc-test/**
          filters:
            - StripPrefix=1
        - id: cc-oss
          uri: lb://oss
          predicates:
            - Path=/cc-oss/**
          filters:
            - StripPrefix=1

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9001/cc-auth/oauth/rsa/publicKey' #RSA公钥接口，用于验证JWT

secure:
  ignore:
    urls: #白名单路径
      - "/cc-user/user/login"
      - "/cc-user/user/register"
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/webjars/springfox-swagger-ui/**"
      - "/actuator/**"


management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
